[sources.filesystem]
bucket_url = "s3://duck-lake/data-swamp/"
file_glob = "*.csv"

[destination.filesystem]
bucket_url = "s3://duck-lake/data-swamp/monthly/"

[extract.data_writer]
file_max_bytes = 5_000_000    # 5MB chunks
file_max_items = 5000         # 5k items per file
buffer_max_items = 2500       # Smaller buffer

[normalize]
workers = 2                   # Reduced worker count
start_method = "spawn"        # Safer process creation
max_parallel_items = 10       # Limit parallel processing

[normalize.data_writer]
file_max_bytes = 2_500_000   # 2.5MB chunks
file_max_items = 2500        # 2.5k items per file
buffer_max_items = 1000      # Minimal buffer size

[load]
workers = 2                  # Minimal worker count        # More workers for parallel file loading