version: 2

sources:
  - name: duck_pond
    description: Raw Google Analytics data loaded through DLT pipeline # Adjust if your duckdb path is different
    schema: source_data               # This matches your dataset_name in the pipeline
    tables:
      - name: load
        description: Root table containing Google Analytics session data including visitor information, device details, and session metrics
        columns:
          - name: _dlt_id
          - name: visit_id 
          - name: full_visitor_id 
          - name: visit_number
          - name: visit_start_time
          - name: date 
          - name: device 
          - name: geo_network
          - name: totals
          - name: traffic_source
      - name: load__hits
        description: Table containing Google Analytics pageview data
        columns:
          - name: _dlt_parent_id
          - name: _dlt_list_idx
          - name: _dlt_id
          - name: time 
          - name: minute
          - name: hour
          - name: hit_number 
          - name: type 
          - name: is_entrance 
          - name: is_interaction 
          - name: is_exit
          - name: e_commerce_action__action_type 
          - name: e_commerce_action__step 
          - name: page__page_title 
          - name: page__hostname 
          - name: page__page_path
          - name: page__page_path_level1
          - name: page__page_path_level2
          - name: page__page_path_level3
          - name: page__page_path_level4
          - name: referer
          - name: app_info__exit_screen_name
          - name: app_info__landing_screen_name
          - name: app_info__screen_depth
          - name: app_info__screen_name
